"""Add parent_account_id and deadline

Revision ID: 09c3b36b1280
Revises: 1cb7e80b52d5
Create Date: 2026-07-13 22:05:51.143808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c3b36b1280'
down_revision: Union[str, Sequence[str], None] = '1cb7e80b52d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('parent_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['parent_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'parent_account_id')
    op.drop_column('jobs', 'deadline')
    # ### end Alembic commands ###
