"""Add foreign key indexes

Revision ID: 1cb7e80b52d5
Revises: ba3bbf7203dc
Create Date: 2026-07-13 01:13:11.216986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb7e80b52d5'
down_revision: Union[str, Sequence[str], None] = 'ba3bbf7203dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_application_id'), 'assessment_results', ['application_id'], unique=False)
    op.create_index(op.f('ix_assessments_job_id'), 'assessments', ['job_id'], unique=False)
    op.drop_constraint('candidate_profiles_user_id_key', 'candidate_profiles', type_='unique')
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_jobs_owner_id'), 'jobs', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_owner_id'), table_name='jobs')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.create_unique_constraint('candidate_profiles_user_id_key', 'candidate_profiles', ['user_id'])
    op.drop_index(op.f('ix_assessments_job_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessment_results_application_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    # ### end Alembic commands ###
